version: "3"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:

  keycloak-db:
    image: postgres:16
    container_name: keycloak-db
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    logging: *default-logging

  mongodb:
    image: mongo:4.4.4
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=books
    logging: *default-logging
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru" ]
    logging: *default-logging
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak
    restart: always
    depends_on:
      - keycloak-db
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm.json
    ports:
      - "8084:8080"
    command: [ "start-dev", "--import-realm" ]
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json
    logging: *default-logging
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  processor:
    build: ./processor
    container_name: processor
    restart: "no"
    environment:
      - MONGODB_URL=mongodb://root:root@mongodb:27017
    depends_on:
      - mongodb
      - redis
      - keycloak
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  books:
    build: ./book-api
    container_name: books_api
    environment:
      - MONGODB_URL=mongodb://root:root@mongodb:27017
      - RESOURCE_SERVER_URL=http://keycloak:8080/realms/code-elevate-realm
      - REDIS_URL=redis
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
      - keycloak
      - processor
    extra_hosts:
      - "host.docker.internal:172.17.0.1"